### ISSUE TITLE
Cityscapes Models Missing

### ISSUE THREAD

**Issue by FBernuy** [itijyou/ademxapp#1]
Hi!

I am trying to test your method trained on the Cityscapes Dataset in another dataset, but couldn't find your model to download. Is it available?

Thanks!

**Comment by codegank** [comment]
This code is a castrated version that does not contain the training code.

**Comment by FBernuy** [comment]
Thanks for your response. Let me explain myself:  I don't want to train your model, but to use it to compare results. 

In the README.md file there are links to download the 'Model A' and 'Model A1' (aar), But there are no links for the 'Model A2, 2 conv.' or 'Model A2, 2 conv., coarse'. 

Are you planning to upload and share these files too?

**Comment by codegank** [comment]
Hi FBernuy, I am not the author of this code. Sorry.  I just checked this code found that the author did not release the training code.

**Comment by FBernuy** [comment]
Hi @codegank Wei, thanks, I'll keep waiting then.

**Comment by BAILOOL** [comment]
Any news about the model for the CityScapes dataset?

**Comment by Fourure** [comment]
Thank you for the CityScapes pretrained model. It's gonna be very usefull.

**Comment by chrisranderson** [comment]
@FBernuy @BAILOOL Cityscapes model A1, 2 conv.: https://cloudstor.aarnet.edu.au/plus/index.php/s/2hbvpro6J4XKVIu (from https://github.com/itijyou/ademxapp/issues/24)

**Comment by FBernuy** [comment]
Thanks!
