### ISSUE TITLE
Scale rates of multiscale test in cityscapes

### ISSUE THREAD

**Issue by yzou2** [itijyou/ademxapp#33]
When I use the given ResNet 38-A1 model pretrained on cityscapes and do single scale testing, I get the mIOU 78.08% at val dataset. 
As shown in the github page of ResNet 38, multiscale testing will boost the mIOU by about 1%. However, when I do multi-scale testing, (scales: 0.75, 0.875, 1) I get the mIOU 77.06%, that is lower than single scale testing. Could anyone tell me the scale rates for boosting the performance dramatically?

**Comment by yzou2** [comment]
I fix the bug by replacing the average operation by max.

**Comment by speedinghzl** [comment]
@yzou2 Could you please provide your code for multiscale testing?
