### ISSUE TITLE
Pretrained models for cityscape needed

### ISSUE THREAD

**Issue by ChidanandKumarKS** [itijyou/ademxapp#36]
cityscapes_rna-a1_cls19_s8_ep-0001.params is not found. From where i had to download this model. Kindly suggest

**Comment by ChidanandKumarKS** [comment]
Got the model. Thanks closing the issue

**Comment by Tetsujinfr** [comment]
can you close the issue for real? (like click on "close the issue" button).
thanks
tets

**Comment by ChidanandKumarKS** [comment]
Iam closing the issue
