### ISSUE TITLE
Imagenet doesn't give 4.7 Top5

### ISSUE THREAD

**Issue by miliadis** [itijyou/ademxapp#4]
Hi, 

I tried Imagenet val set and I got 5.24 top5 with Model A (and worse with Model A1). I use MXNet 0.9.1

**Comment by itijyou** [comment]
This is due to the change of eps from 1e-5 to 0.001 in BatchNorm layers.

CUDNN_BN_MIN_EPSILON is 1e-5 in cuDNN v5.
However, for some unknown reason, BatchNorm failed if eps=1e-5 when I ran the code using P40/P100.

**Comment by itijyou** [comment]
It should be good now.
