### ISSUE TITLE
in the paper  why the crop size is larger than the input size?

### ISSUE THREAD

**Issue by dongzhuoyao** [itijyou/ademxapp#5]
> For networks trained with 224*224 inputs, the testing crop size is 320*320, following the setting used by He et al. [13]. For those with 112*112 and 56*56 inputs, we use 160*160 and 80*80 crops respectively.

as written is the paper,if we take 224\*224 as input size,so why the testing crop size is 320\*320(I think it should also be 224\*224)?

**Comment by itijyou** [comment]
As it says, we do this, `following the setting used by He et al. [13].'
