### ISSUE TITLE
Run Errors, help

### ISSUE THREAD

**Issue by makaspacex** [itijyou/ademxapp#8]
> `python issegm/voc.py --data-root data/ade20k --output output --phase val --weight models/ade20k_rna-a1_cls150_s8_ep-0001.params --split val --test-scales 504 --test-flipping --test-steps 2 --gpus 0`

and I get error `from util import transformer as ts because it is being executed from within the issegm/`

then I add `sys.path.append(os.getcwd())` at issegm/voc.py line 16

rerun 'python issegm/voc.py --data-root data/ade20k --output output --phase val --weight models/ade20k_rna-a1_cls150_s8_ep-0001.params --split val --test-scales 504 --test-flipping --test-steps 2 --gpus 0'

and I get `Traceback (most recent call last):
  File "issegm/voc.py", line 578, in <module>
    _val_impl(args, model_specs, logger)
  File "issegm/voc.py", line 435, in _val_impl
    _, net_args, net_auxs = util.load_params(args.from_model, args.from_epoch)
AttributeError: 'module' object has no attribute 'load_params'
`

so, what should I do next ? Thanks very much!

**Comment by itijyou** [comment]
My suggestion is to first make sure that no unexpected change has been made.
And there should be something in common in Issue #2.

**Comment by makaspacex** [comment]
Hey @itijyou , thanks for the suggestion. The code
 ` _, net_args, net_auxs = util.load_params(args.from_model, args.from_epoch)`
 at `issegm/voc.py` 's  line 432 has a problem: the `util` which should be `util/util.py`  has no function which name is `load_params`, is there something wrong? I don't understand. Thank you so much!

**Comment by xiahouzuoxin** [comment]
@zhuihunmiling , `load_params` not in `util/util.py` but in `util/mxutil.py`

You can modify to:
```python
from util.mxutil import load_params
_, net_args, net_auxs = load_params(args.from_model, args.from_epoch)
```

**Comment by itijyou** [comment]
@zhuihunmiling @xiahouzuoxin Thanks for pointing this out. I have fixed it, probably.
